### ISSUE TITLE
Inconsistet report images after last comments update.

### ISSUE THREAD

**Issue by MicheleGuerriero** [scoop-exam/proji#8]
@affo in the last commit I slightly updated the comments throughout the code, along with the repositioning of few features. This actually makes the class diagram we currently have in the report inconsistent. Can you have a look at my last commit and if you agree with the changes regenerate the diagram too? Unfortunately I still have bad resolution problems in generating the diagram and I did not have time to investigate why.

**Comment by affo** [comment]
I only swapped the logic between commenting:

```
 -- ... Internal State
```

VS

```
 -- Access
```

I used the second one once giving public visibility, while the first one when private.
